
default:
  dry_run: false

github_api:
  end_point: "https://api.github.com/graphql"
  num_discussion: 25
  num_comment: 100
  num_reply: 100
  min_credit: 100
  out_dir: "./out"

index:
  load_local: true
  model_path: "./models"
  model_name: "all-MiniLM-L12-v2"
  show_progress: true
  rawdata: "./rawdata"
  database: "./database"
  dry_run: false

bot:
  db_dir: "./database"
  model_path: "./models"
  model_name: "all-MiniLM-L12-v2"
  top_n: 5
  threshold: 0.3
  load_local: false
  dry_run: false
