name: RANGER - Auto Reply (Discussions)

on:
  discussion:
    types: [created]
permissions:
  contents: read
  discussions: write

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - run: python -m pip install -r requirements.txt

      - name: Show event summary
        run: |
          echo "GITHUB_REPOSITORY=${{ github.repository }}"
          echo "GITHUB_OWNER=${{ github.repository_owner }}"
          echo "GITHUB_REPO=${{ github.event.repository.name }}"
          echo "db = ${{ github.workspace }}/database"
          echo "discussion.number=${{ github.event.discussion.number }}"

      - name: Run bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.event.repository.name }}
          GITHUB_OWNER: ${{ github.repository_owner }}

          DB_DIR: ${{ github.workspace }}/database
          TOP_N: "5"
          THRESHOLD: "0.2"
          MODEL_NAME: "all-MiniLM-L12-v2"
          LOG_LEVEL: DEBUG

        run: |
          python RANGER.py --config config.yaml bot \
            --db-dir "$DB_DIR" \
            --model-name "$MODEL_NAME" \
            --top-n "$TOP_N" \
            --threshold "$THRESHOLD" \
            --debug


